feat: реализованы модели и контроллеры для users и films
almariel4/java-filmorate pull request #3
Opened 2023-03-07 21:51 UTC by almariel4

2023-03-08 20:34 UTC, mikita95 reviewed
Добрый день, Анна :)
Все сделано отлично. Только нужно разобраться с тестами и поправить несколько моментов.

2023-03-08 20:34 UTC, mikita95 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTests.java
> +import org.junit.Before;
Лишние импорты

2023-03-10 21:32 UTC, almariel4 commented on pom.xml
> +        <dependency>
Пробовала убрать. Без явного указания этой зависимости не срабатывает валидация спринга @Valid.
https://stackoverflow.com/questions/27111806/validation-form-in-spring-using-valid-not-work

2023-03-11 13:20 UTC, mikita95 requested changes
Сейчас не проходят тесты, так как вы добавили как-то лишние зависимости.
Попробуйте использовать те зависимости, которые я указал. С ними ваш проект собирается и проходит тесты :)

2023-03-11 13:20 UTC, mikita95 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTests.java
> +    void getAllFilms() {
Лучше не оставлять закомментированных кусков кода в программе :) Так не очень аккуратно

2023-03-11 13:20 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @Email(regexp = ".+[@].+[\\.].+")
Здесь можно не указывать регулярное выражение, сработает и так

2023-03-11 13:22 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public Film(String name, String description, LocalDate releaseDate, int duration) {
Можно просто использовать `@AllArgsConstructor` - id может пригодится при обновлении.
Также можно использовать `@Builder` - так удобнее сконструировать объект, в котором много полей

2023-03-12 09:33 UTC, mikita95 approved these changes
Все отлично :) Можно смержить пул-реквест.

2023-03-13 11:38 UTC, merged