refactor: добавлено взаимодействие с базой
almariel4/java-filmorate pull request #5
Opened 2023-04-21 12:51 UTC by almariel4

2023-04-21 20:51 UTC, mikita95 requested changes
Все сделано очень хорошо. Нужно поправить лишь пару моментов

2023-04-21 20:51 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        jdbcTemplate.update("INSERT INTO LIKES (FILM_ID, USER_ID) " +
Предполагается, что метод PUT (в данном случае addLike) должен быть идемпотентным (то есть несколько вызовов одного и того же метода с одними параметрами, имеет такой же эффект как и один вызов): https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PUT. В данном случае можно просто поменять sql-запрос, использовав команду merge в H2 (https://www.h2database.com/html/commands.html#merge_into) - если запись существует, то это сработает как update, иначе произойдет insert.
Конечно, понятие идемпотентности предполагает в большей степени именно влияние на состояние сервера, а не клиента, и в данном случае состояние не изменится (так как данные не поменяются). Но с точки зрения клиента - это не ошибка, поставить повторно лайк фильму.

2023-04-21 20:51 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        if (!getFilms().containsKey(film.getId())) {
Сейчас для проверки существования записи запрос возвращают всю таблицу, что не очень эффективно (если у нас очень много фильмов). Лучше использовать отдельный запрос, использовав оператор sql `exists`

2023-04-21 20:51 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        if (genres.size() != 0) {
Лучше использовать isEmpty() - так понятнее и короче

2023-04-21 20:51 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDbStorage.java
> +        if (!getUsers().containsKey(user.getId())) {
Сейчас для проверки существования записи запрос возвращают всю таблицу, что не очень эффективно (если у нас очень много фильмов). Лучше использовать отдельный запрос, использовав оператор sql `exists`

2023-04-21 20:51 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDbStorage.java
> +        jdbcTemplate.update("INSERT INTO FRIENDS (USER_ID, FRIEND_ID) " +
Аналогично фильмам, запрос упадет с ошибкой, если попытаться вызвать метод несколько раз подряд

2023-04-21 20:51 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Map<Long, Boolean> friends2 = new HashMap<>();
Лучше выбрать более понятное название поля :)

2023-04-22 14:05 UTC, almariel4 commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        if (!getFilms().containsKey(film.getId())) {
Мне не удалось найти и создать работающих примеров sql-запросов с использованием оператора `exist`, поэтому использовала подсчет возвращаемых строк из БД. Если подскажете хорошую ссылку, будет здорово)

2023-04-22 19:28 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        if (!getFilms().containsKey(film.getId())) {
Да, вы сделали даже лучше :)
Оператор exists можно было бы использовать сразу в запросах обновления (http://www.h2database.com/html/grammar.html#condition), а не отдельно проверять существование.

2023-04-22 19:29 UTC, mikita95 approved these changes
Все сделано хорошо. Можно мержить пул-реквест

2023-04-23 11:11 UTC, merged